### ISSUE TITLE
tele-op controls delivery

### ISSUE THREAD

**Issue by Archer1423** [HF-Robotics/ftc_app#21]
- delivery mech activation/deactivation
- sorting (automate)
     - limits(timeout, sensor, manual override)
-automate lift
     - limits (timeout, sensor, manual override)
- automate trip
      - limits (timeout, sensor, manual override) 
-full automation (one button)
     - limits (timeout, sensor, manual override)

**Comment by markdmatthews** [comment]
Implemented.
